version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pos-mysql
    environment:
      MYSQL_DATABASE: pos_db
      MYSQL_ROOT_PASSWORD: Sahu@177
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos-backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/pos_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=Sahu@177
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
